apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: open-cluster-management
spec:
  channel: release-2.11
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace